# Generated by Django 2.2.2 on 2019-07-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('albums', models.CharField(max_length=100)),
                ('song', models.CharField(max_length=100)),
            ],
        ),
    ]
